### PR TITLE
Set Socket Timeout for input stream from socket.

### PR DESCRIPTION
**Pull request by hideki**
TJWS set SO_TIMEOUT 0 in Serve.java. It causes hanging state in listener.

### CODE REVIEW

**Comment by NitzDKoder** [comment]
@hideki 
With context tohttps://github.com/couchbase/couchbase-lite-java-listener/issues/83
 
we set var DEFAULT_TIMEOUT = 5 * 60 * 1000 // 5 minutes

 https://github.com/couchbaselabs/TodoLite-PhoneGap/blob/f1a810f9408a9807f3bf25ae69ba1d6a6aaee71c/js/modules.js#L1205

https://github.com/couchbase/couchbase-lite-java-listener/blob/1.4.0/src/main/java/com/couchbase/lite/listener/LiteServlet.java#L106


How is this DEFAULT_TIMEOUT and setSoTimeout works in co-ordination?

https://github.com/couchbase/couchbase-lite-java-listener/blob/1.4.0/vendor/tjws/src/java/Acme/Serve/Serve.java#L2130
https://github.com/couchbase/couchbase-lite-java-listener/blob/1.4.0/vendor/tjws/src/java/Acme/Serve/Serve.java#L2151
https://github.com/couchbase/couchbase-lite-java-listener/blob/1.4.0/vendor/tjws/src/java/Acme/Serve/Serve.java#L2158

On timeout the socket is closed..hwo does the client comes to know this event..


Thanks
Nithin

**Comment by hideki** [comment]
With current architecture, it does not expect that Listener (server) needs to wait for the request from the client (javascript). The server-side timeout could happen if a connection failure occurs during the client is sending a request.

**Comment by NitzDKoder** [comment]
@hideki 


"The server-side timeout could happen if a connection failure occurs during the client is sending a request."
as we are 127.0.0.1 loopback address kind of server running..how the lte network is causing an issue here?

**Comment by hideki** [comment]
@NitzDKoder,
> as we are 127.0.0.1 loopback address kind of server running..how the lte network is causing an issue here?

Honestly, I don't know. Even I am not sure if LTE causes this problem. It seems this is Android OS level issue.

**Pull request merged**
